package com.example.localization

import androidx.compose.runtime.Composable
import androidx.compose.ui.text.style.TextAlign

object Loc {
    // Supported Languages
    const val EN = "en"
    const val UR = "ur"

    private val translations = mapOf(
        EN to mapOf(
            "app_name" to "Smart Hisab",
            "dashboard" to "Dashboard",
            "products" to "Products",
            "add_product" to "Add Product",
            "billing" to "Billing",
            "customers" to "Customers",
            "reports" to "Reports",
            "expenses" to "Expenses",
            "settings" to "Settings",
            "login" to "Login",
            "signup" to "Signup",
            "logout" to "Logout",
            "today_sales" to "Today's Sales",
            "today_profit" to "Today's Profit",
            "total_udhaar" to "Total Udhaar",
            "low_stock" to "Low Stock",
            "create_bill" to "Create Bill",
            "save" to "Save",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "edit" to "Edit",
            "search" to "Search",
            "welcome_back" to "Welcome Back",
            "tagline" to "Secure Digital Ledger & Accounting Book",
            "shop_name" to "Shop or Business Name",
            "owner_name" to "Owner Name",
            "phone" to "Phone Number (Optional)",
            "email" to "Email Address",
            "password" to "Password",
            "language" to "Language",
            "select_language" to "Select Language",
            "english" to "English",
            "urdu" to "اردو (Urdu)",
            "onboard_date" to "Onboard Date",
            "recent_ledger" to "RECENT LEDGER ENTRIES",
            "ledger_summary" to "LEDGER SUMMARY",
            "net_balance" to "Net Balance",
            "cash_in" to "Cash In",
            "cash_out" to "Cash Out",
            "quick_test" to "💡 Quick Test: email: demo@hisab.com / password: password",
            "business_details" to "BUSINESS DETAILS",
            "account_credentials" to "ACCOUNT CREDENTIALS",
            "register_business" to "REGISTER BUSINESS",
            "no_account" to "Don't have an account?",
            "already_account" to "Already have an account?",
            "login_account" to "LOGIN TO ACCOUNT",
            "active_ledger" to "ACTIVE LEDGER",
            "proprietor" to "Proprietor",
            "demo_banner" to "Smart Hisab is in simulated Offline Mode. Data is persisted securely in local device memory.",
            "low_stock_desc" to "Items running out of stock",
            "reports_desc" to "Sales, profits, and expense sheets",
            "manage_expenses" to "Manage Business Expenses",
            "manage_customers" to "Manage Customer Udhaar & Credits",
            "manage_products" to "Product Inventory & Stock control",
            "create_invoice" to "Quick Customer Billing & Invoicing",
            "custom_greeting" to "Hello,",
            "currency_label" to "CURRENCY",
            "active_cloud" to "CLOUD CONFIG: SECURE",
            "offline_cloud" to "LOCAL OFFLINE SYNC",
            "demo_local_mode" to "DEMO LOCAL MODE (NO GOOGLE-SERVICES.JSON)",
            "this_month_sales" to "This Month Sales",
            "this_month_expenses" to "This Month Expenses",
            "net_profit" to "Net Profit",
            "low_stock_count" to "Low Stock Products",
            "total_products" to "Total Products",
            "new_bill" to "New Bill",
            "add_customer" to "Add Customer",
            "add_expense" to "Add Expense",
            "view_reports" to "View Reports",
            "offline_banner" to "Offline mode • Using cached data. Changes will sync automatically.",
            "restock" to "Restock",
            "current_stock" to "Current Stock",
            "low_stock_limit" to "Low Stock Limit",
            "quantity_to_add" to "Quantity to Add",
            "optional_note" to "Purchase / Restock Note (Optional)",
            "save_update" to "Save Stock Update",
            "low_stock_alert" to "LOW STOCK ALERTS"
        ),
        UR to mapOf(
            "app_name" to "سمارٹ حساب",
            "dashboard" to "ڈیش بورڈ",
            "products" to "پروڈکٹس",
            "add_product" to "پروڈکٹ شامل کریں",
            "billing" to "بلنگ",
            "customers" to "گاہک",
            "reports" to "رپورٹس",
            "expenses" to "اخراجات",
            "settings" to "سیٹنگز",
            "login" to "لاگ ان",
            "signup" to "سائن اپ",
            "logout" to "لاگ آؤٹ",
            "today_sales" to "آج کی فروخت",
            "today_profit" to "آج کا منافع",
            "total_udhaar" to "کل ادھار",
            "low_stock" to "کم اسٹاک",
            "create_bill" to "بل بنائیں",
            "save" to "محفوظ کریں",
            "cancel" to "منسوخ کریں",
            "delete" to "حذف کریں",
            "edit" to "ترمیم کریں",
            "search" to "تلاش کریں",
            "welcome_back" to "خوش آمدید",
            "tagline" to "محفوظ ڈیجیٹل لیجر اور کھاتہ بک",
            "shop_name" to "دکان یا کاروبار کا نام",
            "owner_name" to "مالک کا نام",
            "phone" to "فون نمبر (اختیاری)",
            "email" to "ای میل ایڈریس",
            "password" to "پاس ورڈ",
            "language" to "زبان",
            "select_language" to "زبان منتخب کریں",
            "english" to "English (انگریزی)",
            "urdu" to "اردو",
            "onboard_date" to "شامل ہونے کی تاریخ",
            "recent_ledger" to "حالیہ کھاتہ اندراجات",
            "ledger_summary" to "کھاتہ کا خلاصہ",
            "net_balance" to "کل بقایا رقم",
            "cash_in" to "آمدنی (کیش ان)",
            "cash_out" to "اخراجات (کیش آؤٹ)",
            "quick_test" to "💡 فوری ٹیسٹ: ای میل: demo@hisab.com / پاس ورڈ: password",
            "business_details" to "کاروبار کی تفصیلات",
            "account_credentials" to "اکاؤنٹ کی تفصیلات",
            "register_business" to "کاروبار رجسٹر کریں",
            "no_account" to "کیا آپ کا اکاؤنٹ نہیں ہے؟",
            "already_account" to "پہلے سے اکاؤنٹ موجود ہے؟",
            "login_account" to "اکاؤنٹ میں لاگ ان کریں",
            "active_ledger" to "فعال لیجر",
            "proprietor" to "پروپرائیٹر / مالک",
            "demo_banner" to "سمارٹ حساب آف لائن موڈ میں کام کر رہا ہے۔ آپ کا ڈیٹا محفوظ طریقے سے موبائل میں محفوظ ہے۔",
            "low_stock_desc" to "وہ اشیاء جن کا اسٹاک ختم ہونے والا ہے",
            "reports_desc" to "فروخت، منافع، اور اخراجات کی رپورٹ",
            "manage_expenses" to "کاروباری اخراجات کا انتظام کریں",
            "manage_customers" to "گاہکوں کے ادھار اور کریڈٹ کا انتظام",
            "manage_products" to "مصنوعات کا اسٹاک اور انوینٹری کنٹرول",
            "create_invoice" to "فوری بلنگ اور انوائس تیار کریں",
            "custom_greeting" to "خوش آمدید،",
            "currency_label" to "کرنسی",
            "active_cloud" to "کلاؤڈ کنکشن: محفوظ",
            "offline_cloud" to "لوکل آف لائن سنک",
            "demo_local_mode" to "ڈیمو لوکل موڈ (بغیر کلاؤڈ فائل)",
            "this_month_sales" to "اس ماہ کی فروخت",
            "this_month_expenses" to "اس ماہ کے اخراجات",
            "net_profit" to "خالص منافع",
            "low_stock_count" to "کم اسٹاک پروڈکٹس",
            "total_products" to "کل پروڈکٹس",
            "new_bill" to "نیا بل بنائیں",
            "add_customer" to "گاہک شامل کریں",
            "add_expense" to "خرچ شامل کریں",
            "view_reports" to "رپورٹس دیکھیں",
            "offline_banner" to "آف لائن موڈ • لوکل ڈیٹا استعمال کیا جا رہا ہے۔ انٹرنیٹ آنے پر کلاؤڈ سنک ہو جائے گا۔",
            "restock" to "اسٹاک بڑھائیں",
            "current_stock" to "موجودہ اسٹاک",
            "low_stock_limit" to "کم اسٹاک کی حد",
            "quantity_to_add" to "اضافی اسٹاک کی تعداد",
            "optional_note" to "خریداری / اسٹاک بڑھانے کا نوٹ (اختیاری)",
            "save_update" to "اسٹاک اپ ڈیٹ محفوظ کریں",
            "low_stock_alert" to "کم اسٹاک الرٹس"
        )
    )

    // Retrieve translated string or fallback to key itself
    fun t(lang: String, key: String): String {
        return translations[lang]?.get(key) ?: translations[EN]?.get(key) ?: key
    }

    // Get suitable text alignment based on language direction
    fun getAlign(lang: String): TextAlign {
        return if (lang == UR) TextAlign.Right else TextAlign.Left
    }

    // Get layout direction boolean
    fun isRtl(lang: String): Boolean {
        return lang == UR
    }
}
